spring:
  application:
    name: school

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: Postgresql@Om123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true


  sql:
    init:
      mode : always
      data-locations: classpath:data.sql

jwt:
  secret: j74hdwhduydiw3387r3893r833838vn9vqnnufwenwevw85wvuvoin98r90839423
